name: markdownlint

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install markdownlint-cli
      - name: Run markdownlint
        run: npx markdownlint 'docs/index.md' --config .markdownlint.json --ignore docs/*.md
