name: Run Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          SKIP_TESTS: true
        run: |
          if [ -z "$SKIP_TESTS" ]; then
            npm run test
          else
            echo "Skipping tests due to environment variable."
          fi
